import {
  faBookmark,
  faPencil,
  faVideo,
  faMusic,
  faGuitar,
  faMicrophone,
  faPodcast,
  faHome,
  faPhone,
  faStar,
  faHeart,
  faPoo,
  faComment,
  faPaperclip,
  faTruckFast,
  faCameraRetro,
  faXmark,
  faCloud,
  faCalendarDays,
  faFaceSmile,
  faBell,
  faBomb,
  faCartShopping,
  faMugHot,
  faGhost,
  faCar,
  faBolt,
  faFile,
  faGear,
  faTrash,
  faInbox,
  faCircleUp,
  faCircleDown,
  faTag,
  faBarcode,
  faLock,
  faHeadphones,
  faBook,
  faCircleUser,
  faRotateRight,
  faDroplet,
  faFont,
  faPlane,
  faFire,
  faEye,
  faThumbsUp,
  faCircleExclamation,
  faHand,
  faPaperPlane,
  faCode,
  faThumbstack,
  faKey,
  faFolder,
  faCity,
  faTicket,
  faTree,
  faWifi,
  faHashtag,
  faBicycle,
  faCompass,
  faAddressBook,
  faBrush,
  faEarthAmericas,
  faSnowflake,
  faFish,
  faLink,
  faSun,
  faHandshake,
  faAnchor,
  faClock,
  faCross,
  faCircle,
  faInfo,
  faQuestion,
  faPassport,
  faFlag,
  faBuilding,
  faStore
} from '@fortawesome/free-solid-svg-icons';


export const commonIcons = [
  // Media and Communication
  faBookmark, faPencil, faVideo, faMusic, faGuitar, faMicrophone, faPodcast,
  faCameraRetro, faHeadphones, faBell,

  // UI Elements
  faXmark, faTag, faCircleUp, faCircleDown, faCircleExclamation, faCircle,
  faCircleUser, faInfo, faQuestion,

  // Everyday Objects & People
  faPhone, faCartShopping, faMugHot, faCar, faKey, faFolder, faAddressBook,
  faBook, faPaperclip, faHand, faPaperPlane, faThumbstack,

  // Emotions & Signs
  faStar, faHeart, faPoo, faFaceSmile, faComment, faGhost, faBomb, faSun,
  faSnowflake, faFish, faHandshake, faEarthAmericas,

  // Commerce & Office
  faBarcode, faTrash, faInbox, faLock, faGear, faFile, faTicket, faStore,
  faBuilding, faPassport, faFlag,

  // Nature & Geography
  faTree, faWifi, faBicycle, faCompass, faBrush, faAnchor, faCity, faFire,
  faLink, faPlane, faHashtag, faClock, faCross
];
