import {
  faBookmark,
  faPencil,
  faVideo,
  faMusic,
  faGuitar,
  faMicrophone,
  faPodcast,
  faHome,
  faPhone,
  faStar,
  faHeart,
  faPoo,
  faComment,
  faPaperclip,
  faTruckFast,
  faCameraRetro,
  faXmark,
  faCloud,
  faCalendarDays,
  faFaceSmile,
  faBell,
  faBomb,
  faCartShopping,
  faMugHot,
  faGhost,
  faCar,
  faBolt,
  faFile,
  faGear,
  faTrash,
  faInbox,
  faCircleUp,
  faCircleDown,
  faTag,
  faBarcode,
  faLock,
  faHeadphones,
  faBook,
  faCircleUser,
  faRotateRight,
  faDroplet,
  faFont,
  faPlane,
  faFire,
  faEye,
  faThumbsUp,
  faCircleExclamation,
  faHand,
  faPaperPlane,
  faCode,
  faThumbTack,
  faKey,
  faFolder,
  
  faTicket,
  faTree,
  faWifi,
  faHashtag,
  faBicycle,
  faCompass,
  faAddressBook,
  
  faEarthAmericas,
  faSnowflake,
  faFish,
  faLink,
  faSun,
  faHandshake,
  faAnchor,
  faClock,
  faCross,
  faInfo,
  faQuestion,
  faPassport,
  faFlag,
  faBuilding,
  faStore,
  faAddressCard,
  faRocket,
  faRegistered,
  faDesktop,
  faMoon,
  faLanguage,
  faSignal,
  faTrain,
  faTrophy,
  faCrown,
  faMask,
  faCircleCheck,
  faLightbulb
} from '@fortawesome/free-solid-svg-icons';
export const commonIcons = [
  // Media and Communication
  faBookmark, faPencil, faVideo, faMusic, faGuitar, faMicrophone, faPodcast,
  faCameraRetro, faHeadphones, faBell,

  // UI Elements
  faXmark, faTag, faCircleUp, faCircleDown, faCircleExclamation,
  faCircleUser, faCircleCheck, faInfo, faQuestion,

  // Everyday Objects & People
  faPhone, faCartShopping, faMugHot, faCar, faKey, faFolder, faAddressBook,
  faBook, faPaperclip, faHand, faPaperPlane, faThumbTack, faAddressCard,

  // Emotions & Signs
  faStar, faHeart, faPoo, faFaceSmile, faComment, faGhost, faBomb, faSun,
  faSnowflake, faFish, faHandshake, faEarthAmericas, faMoon, faMask, faLightbulb,

  // Commerce & Office
  faBarcode, faTrash, faInbox, faLock, faGear, faFile, faTicket, faStore,
  faBuilding, faPassport, faFlag,

  // Technology and Transport
  faWifi, faBicycle, faCompass,  faAnchor,  faFire,
  faLink, faPlane, faHashtag, faClock, faCross, faDesktop, faRocket,
  faSignal, faTrain,

  // Achievement and Organization
  faTrophy, faCrown, faRegistered
];
